server:
  port: 8189

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  application:
    name: Spring-Authorization-Server
  datasource:
    url: jdbc:mariadb://localhost:3306/spring-oauth-server
    username: root
    password: smart
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
      javax:
        persistence:
          sharedCache:
            mode: ALL